try:
    assuyahd()
except Exception as erro:
    print("ERRO LOCALIZADO: ",erro)
